### ISSUE TITLE
Minor change to instructions to avoid confusion.

### ISSUE THREAD

**Issue by anmghstnet** [prestomation/resmed_myair_sensors#18]
In line 7 of the setup instructions, change "HA" to "HACS".

This avoids people attempting to add the integration via the normal HA integration menu. (Which it does do, it just doesn't work!)

In the HA**CS** UI go to "Configuration" -> "Integrations" click "+" and search for "ResMed myAir CPAP Sensors"

Note: Thanks for making this integration, you're awesome!

**Comment by prestomation** [comment]
These instructions are techniclly correct for those installing from source and they come from a common template that many custom components use.

That said, I agree it would be less confusing to put HACS-specific instructions first and to be more clear in the instructions

I'm glad you're able to use the integration! I would love to hear any useful automations you have built around this data.
