### ISSUE TITLE
Allow multiple CPAP devices to be tracked

### ISSUE THREAD

**Issue by aurvandel** [prestomation/resmed_myair_sensors#3]
**Is your feature request related to a problem? Please describe.**
We have multiple CPAP users in our house but this integration is only able to track the 1st machine that was added

**Describe the solution you'd like**
I would like to be able to monitor multiple CPAP machines

**Describe alternatives you've considered**
My only work around I've found that remotely works is that if I disable the currently working device and reboot home assistant it will then pick up the second device. This is not really a feasible solution obviously.

**Additional context**
![image](https://user-images.githubusercontent.com/6406075/148263386-9109dd6f-ca21-4ef4-ab6d-0c2c0f2c74a8.png)

**Comment by prestomation** [comment]
Thanks for filing the issue. I will need some help here as I don't have multiple devices. Do you have one login with multiple devices, or multiple logins(2 people)?

**Comment by aurvandel** [comment]
> Thanks for filing the issue. I will need some help here as I don't have multiple devices. Do you have one login with multiple devices, or multiple logins(2 people)? Are you in US or EU?

Each device requires a separate login.

**Comment by prestomation** [comment]
Are you sure this doesn't already work? I think you can add the integration again for the second user. If this doesn't work, I will need more information. Do you see errors in the logs?

**Comment by aurvandel** [comment]
Not sure if this error is from me trying to add the device without deleting first or if it's related to adding the second user.
```
Logger: homeassistant.components.sensor
Source: custom_components/resmed_myair/sensor.py:67
Integration: Sensor (documentation, issues)
First occurred: 10:53:31 AM (2 occurrences)
Last logged: 10:53:31 AM

Error adding entities for domain sensor with platform resmed_myair
Error while setting up resmed_myair platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 363, in state
    value = self.native_value
  File "/config/custom_components/resmed_myair/sensor.py", line 67, in native_value
    value = datetime.strptime(value, "%Y-%m-%d")
TypeError: strptime() argument 1 must be str, not int
```

**Comment by aurvandel** [comment]
When I look at the sensor in developer tools all of them are a 0 for the second machine except for sensor.cpap_last_sleep_date_recorded2 which does not show up at all.

**Comment by prestomation** [comment]
Ok great I should be able to address this in the next few days. Thanks for the info.

**Comment by aurvandel** [comment]
No worries, take your time. Let me know if you need anything more from me and thanks for looking into this.

**Comment by prestomation** [comment]
Sorry I didn't mean to close this, just meant to refer to it.

But I have found an issue that might have caused this. Please update your installation and let me know if it works

**Comment by aurvandel** [comment]
Initial tests are looking good. I'll let you know if anything breaks overnight after the machines communicate with ResMed's servers again.
![image](https://user-images.githubusercontent.com/6406075/148819296-1f9eef26-7da5-4ae4-9423-76abb37cc0cd.png)

**Comment by prestomation** [comment]
Nice! I'm going to close this but feel free to reopen if you have any issues with two CPAPs, or please file a new issue if you encounter different problems.
