### ISSUE TITLE
Error on HA 2023.5.0

### ISSUE THREAD

**Issue by justin654** [prestomation/resmed_myair_sensors#33]
Integration was working fine until I just did this latest update. Not really sure how to resolve it. Anyone have any suggestions?

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/resmed_myair/__init__.py:23
Integration: ResMed myAir CPAP Sensors (documentation, issues)
First occurred: 11:23:36 PM (1 occurrences)
Last logged: 11:23:36 PM

```
Error setting up entry ResMed-AirSense11 AutoSet for resmed_myair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/resmed_myair/__init__.py", line 23, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

```

**Comment by Bosswaffle** [comment]
This is a duplicate of #30 "Change to async_forward_entry_setups"

**Comment by justin654** [comment]
Thanks, resolved with that!
