### ISSUE TITLE
Solidify beta/release process

### ISSUE THREAD

**Issue by prestomation** [prestomation/resmed_myair_sensors#5]
**Is your feature request related to a problem? Please describe.**
Today HACS users pull directly from master. There is no good way to test changes with certain users without impacting all users

**Describe the solution you'd like**
Start publishing prod/prerelease releases, and ask these beta users to use prerelease versions through HACCS

**Describe alternatives you've considered**
Sending zip files of prerelease files

**Additional context**
N/A

**Comment by prestomation** [comment]
I've got release drafter and automatic zips-on-release setup which all seems good and provides changelogs in the release notes.

All that is left is to test that checking pre-release works as expected with HACS and the release process. I'll test this with the next feature ask/PR.

**Comment by Dorval1** [comment]
hi there,
i guess i need help
i couldn't find this sensor in HACS, so i've done a manual install with the custom component but got an "Unknown error occurred" when i try to configure it
i'm using the EU(Experimental) region and found this error in HA log
i'm not sure if i did something wrong or if this is a bug
maybe you can have a look and give me some insight ?
[error.log](https://github.com/prestomation/resmed_myair_sensors/files/8022099/error.log)
