### ISSUE TITLE
Unavailble 

### ISSUE THREAD

**Issue by mikefrantz** [prestomation/resmed_myair_sensors#50]
## Configuration
 Core 2024.8.1
Supervisor 2024.08.0
Operating System 13.0
Frontend 20240809.0

```yaml

Add your logs here.

```

## Describe the bug
None of the entities come in after the last update. Everything worked with core version 2024.07.x

![image](https://github.com/user-attachments/assets/7fa2b010-fd7d-4f41-acfd-d09a5a178fa6)

## Debug log

```text

Add your logs here.

```

**Comment by mikefrantz** [comment]
None of the entities come in after the update from 2024.7.x to 2024.8.1

**Comment by Anto79-ops** [comment]
oh I guess we have duplicate issues, I'm seeing the same and posted loges here:

https://github.com/prestomation/resmed_myair_sensors/issues/48

**Comment by c3p0vsr2d2** [comment]
+1

**Comment by mikefrantz** [comment]
Mine still is not working. Is there something I need to do on my end to get it working?
