### ISSUE TITLE
Does integration work in Austalia?

### ISSUE THREAD

**Issue by MarcRaynor** [prestomation/resmed_myair_sensors#65]
I’m getting a message saying “ This entity is no longer being provided by the hacs integration. If the entity is no longer in use, delete it in settings.”

**Comment by Snuffy2** [comment]
Sorry for the belated reply. Have you been able to get your issue fixed?

**Comment by MarcRaynor** [comment]
Hi
I was able to get around that issue but because I live in Australia I
wasn’t able to  get the integration to work.
Thanks
Marc

**Comment by Snuffy2** [comment]
Try setting it up with a region of North America. Taking a quick look, the MyAir ResMed codes for North America and Australia look the same.

**Comment by HeapsGoodTom** [comment]
I am in Australia and can confirm that connecting MyAir to this integration worked for me today by selecting North America.

**Comment by MarcRaynor** [comment]
I got it to work, thanks for your help :)
