### ISSUE TITLE
Register service to force refresh

### ISSUE THREAD

**Issue by blhoward2** [prestomation/resmed_myair_sensors#8]
**Is your feature request related to a problem? Please describe.**
At present, there can be an up to 30 minute delay before the data is refreshed after the machine is turned off.

**Describe the solution you'd like**
It would be useful for there to be a service registered that force refreshed the integration's data, that way it could be triggered via an automation to refresh when the CPAP machine turns off (assuming energy monitoring to monitor that separately). This would allow fresh data to be displayed on dashboards and the like.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**

**Comment by prestomation** [comment]
Thanks for the feature request! I've pushed a new version that adds a force poll service for each config entry. Please feel free to open if you have any issues, thanks!

**Comment by blhoward2** [comment]
That’s was fast! Seems to be working perfectly. Thanks for putting in all the work to reverse engineer the login system!
